<a href="https://colab.research.google.com/github/aryann402/data-science/blob/main/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/World Cup 2018 Dataset.csv")

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN


In [ ]:
import pandas as pd
dataframe = pd.read_csv("/content/drive/MyDrive/World Cup 2018 Dataset.csv")
dataframe

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN


In [ ]:
dataframe=pd.read_csv("/content/drive/MyDrive/World Cup 2018 Dataset.csv")
dataframe

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN


In [ ]:
dataframe.tail(10)

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
23,Korea,F,9.0,0.0,0.0,1.0,59.0,Sweden,12.0,-1.0,-2.0,Mexico,28.0,-1.0,-10.0,Germany,43.0,-1.0,0.0,NaN
24,Belgium,G,12.0,0.0,0.0,1.0,5.0,Panama,13.0,NaN,NaN,Tunisia,29.0,0.0,0.0,England,45.0,-17.0,-70.0,NaN
25,Panama,G,0.0,0.0,0.0,0.0,56.0,Belgium,13.0,NaN,NaN,England,30.0,NaN,NaN,Tunisia,46.0,NaN,NaN,NaN
26,Tunisia,G,4.0,0.0,0.0,0.0,27.0,England,14.0,-1.0,-2.0,Belgium,29.0,0.0,0.0,Panama,46.0,NaN,NaN,NaN
27,England,G,14.0,1.0,1.0,2.0,15.0,Tunisia,14.0,1.0,2.0,Panama,30.0,NaN,NaN,Belgium,45.0,17.0,70.0,NaN
28,Poland,H,7.0,0.0,0.0,2.0,7.0,Senegal,15.0,NaN,NaN,Columbia,31.0,NaN,NaN,Japan,47.0,2.0,3.0,NaN
29,Senegal,H,1.0,0.0,0.0,0.0,23.0,Poland,15.0,NaN,NaN,Japan,32.0,2.0,3.0,Columbia,48.0,0.0,0.0,NaN
30,Columbia,H,5.0,0.0,0.0,0.0,13.0,Japan,16.0,2.0,2.0,Poland,31.0,NaN,NaN,Senegal,48.0,0.0,0.0,NaN
31,Japan,H,5.0,0.0,0.0,0.0,55.0,Columbia,16.0,-2.0,-2.0,Senegal,32.0,-2.0,-3.0,Poland,47.0,-2.0,-3.0,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [ ]:
dataframe.head(20)

,Team,Group,Previous \nappearances,Previous \ntitles,Previous\n finals,Previous\n semifinals,Current \nFIFA rank,First match \nagainst,Match index,history with \nfirst opponent\n W-L,history with\n first opponent\n goals,Second match\n against,Match index.1,history with\n second opponent\n W-L,history with\n second opponent\n goals,Third match\n against,Match index.2,history with\n third opponent\n W-L,history with\n third opponent\n goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN
5,Spain,B,14.0,1.0,1.0,2.0,6.0,Portugal,3.0,12.0,31.0,Iran,20.0,NaN,NaN,Morocco,36.0,5.0,7.0,NaN
6,Morocco,B,4.0,0.0,0.0,0.0,40.0,Iran,4.0,-2.0,-2.0,Portugal,19.0,1.0,2.0,Spain,36.0,-5.0,-7.0,NaN
7,IRAN,B,4.0,0.0,0.0,0.0,32.0,Morocco,4.0,2.0,2.0,Spain,20.0,NaN,NaN,Portugal,35.0,-2.0,-5.0,NaN
8,France,C,14.0,1.0,2.0,5.0,9.0,Australia,5.0,1.0,6.0,Peru,21.0,-1.0,-1.0,Denmark,37.0,4.0,9.0,NaN
9,Australia,C,4.0,0.0,0.0,0.0,39.0,France,5.0,-1.0,-6.0,Denmark,22.0,-1.0,-3.0,Peru,38.0,NaN,NaN,NaN


In [ ]:
type(dataframe)

pandas.core.frame.DataFrame

In [ ]:
dataframe.dtypes

,0
Team,object
Group,object
Previous \nappearances,float64
Previous \ntitles,float64
Previous\n finals,float64
Previous\n semifinals,float64
Current \nFIFA rank,float64
First match \nagainst,object
Match index,float64
history with \nfirst opponent\n W-L,float64


In [ ]:
dataframe[["Team","Group"]]

,Team,Group
0,Russia,A
1,Saudi Arabia,A
2,Egypt,A
3,Uruguay,A
4,Porugal,B
5,Spain,B
6,Morocco,B
7,IRAN,B
8,France,C
9,Australia,C


In [ ]:
dataframe.shape

(33, 20)

In [6]:
import numpy as np
a=np.array([1,5,6,9,10])
print(a)

[ 1  5  6  9 10]


In [ ]:
b=np.array((10,20,30,))

In [9]:
a=np.array([[1,2,3],
            [4,5,6]])

In [10]:
print(a.shape)

(2, 3)


In [11]:
print(a.size)

6


In [13]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
a=np.array([10,20,30,40,50])
a[1:4]

array([20, 30, 40])

In [15]:
a=np.array([1,2,3,])
a+10

array([11, 12, 13])

In [16]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [17]:
a=np.array([2,3,6,8])
res=np.mean(a)
print(res)
result=np.sum(a)
print(result)

4.75
19


In [18]:
a=np.array([7,2,8,1])
np.sort(a)

array([1, 2, 7, 8])

In [19]:
a=np.array([10,20,30,20])
np.where(a==20)

(array([1, 3]),)

In [20]:
a=np.array([1,2,3,4,5,6])
a[a%2==0]

array([2, 4, 6])

In [21]:
a=np.array([1,2,3,4,5,6])
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [22]:
for num in range(2, 52):
    is_prime = True

    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(num, end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 

In [23]:
import pandas as pd
df= pd.read_csv('/gdrive/MyDrive/dataset1.csv')
df1= pd.read_csv('/gdrive/MyDrive/dataset2.csv')
df.head(12)

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No
4,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,NaN,87.0,61000.0,Yes
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes
6,107,Karan,Male,22,Pune,BBA,4,70.0,68.0,75.0,NaN,47000.0,No
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes
8,109,Vikas,Male,21,Lucknow,BCA,2,60.0,65.0,70.0,80.0,48000.0,No
9,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes


In [24]:
df1.head()

,Student_ID,Company,Package_LPA
0,101,TCS,4.5
1,103,Infosys,5.2
2,105,Accenture,6.0
3,106,Capgemini,5.0
4,108,Google,18.0


In [25]:
merging=pd.merge(df,df1,on="Student_ID")
merging

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,TCS,4.5
1,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,Infosys,5.2
2,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,NaN,87.0,61000.0,Yes,Accenture,6.0
3,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,Capgemini,5.0
4,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,Google,18.0
5,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes,Microsoft,24.0
6,112,Kriti,Female,21,Mumbai,Btech,4,91.0,89.0,90.0,97.0,NaN,Yes,Amazon,20.0
7,115,Deepak,Male,23,Lucknow,Btech,4,NaN,93.0,91.0,94.0,64000.0,Yes,Wipro,4.2


In [26]:
kk=pd.concat([df,df1],axis=1)
kk

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No,103.0,Infosys,5.2
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No,106.0,Capgemini,5.0
4,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,NaN,87.0,61000.0,Yes,108.0,Google,18.0
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,110.0,Microsoft,24.0
6,107,Karan,Male,22,Pune,BBA,4,70.0,68.0,75.0,NaN,47000.0,No,112.0,Amazon,20.0
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,115.0,Wipro,4.2
8,109,Vikas,Male,21,Lucknow,BCA,2,60.0,65.0,70.0,80.0,48000.0,No,NaN,NaN,NaN
9,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes,NaN,NaN,NaN


In [27]:
kk.isnull()

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
9,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True


In [28]:
kk.fillna(0)

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No,103.0,Infosys,5.2
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No,106.0,Capgemini,5.0
4,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,0.0,87.0,61000.0,Yes,108.0,Google,18.0
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,110.0,Microsoft,24.0
6,107,Karan,Male,22,Pune,BBA,4,70.0,68.0,75.0,0.0,47000.0,No,112.0,Amazon,20.0
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,115.0,Wipro,4.2
8,109,Vikas,Male,21,Lucknow,BCA,2,60.0,65.0,70.0,80.0,48000.0,No,0.0,0,0.0
9,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes,0.0,0,0.0


In [29]:
kk.dropna()

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No,103.0,Infosys,5.2
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No,106.0,Capgemini,5.0
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,110.0,Microsoft,24.0
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,115.0,Wipro,4.2


In [30]:
kk["English"].fillna(df["English"].mean())

,English
0,90.000000
1,84.000000
2,89.000000
3,80.000000
4,85.307692
5,94.000000
6,75.000000
7,92.000000
8,70.000000
9,98.000000


In [31]:
df["Attendance"].fillna(df["Attendance"].median())

,Attendance
0,92.0
1,95.0
2,88.0
3,90.0
4,87.0
5,98.0
6,91.5
7,96.0
8,80.0
9,99.0


In [32]:
kk.loc[0]
kk.loc[0:3]

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No,103.0,Infosys,5.2
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No,106.0,Capgemini,5.0


In [33]:
kk.iloc[0:3,0:4]

,Student_ID,Name,Gender,Age
0,101,Rahul,Male,20
1,102,Priya,Female,21
2,103,Amit,Male,22


In [34]:
kk["Maths"]>80

,Maths
0,True
1,False
2,True
3,False
4,True
5,True
6,False
7,True
8,False
9,True


In [35]:
kk[kk["Maths"]>80]

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
4,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,NaN,87.0,61000.0,Yes,108.0,Google,18.0
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,110.0,Microsoft,24.0
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,115.0,Wipro,4.2
9,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes,NaN,NaN,NaN
10,111,Arjun,Male,20,Jaipur,BCA,2,82.0,79.0,NaN,91.0,51000.0,No,NaN,NaN,NaN
11,112,Kriti,Female,21,Mumbai,Btech,4,91.0,89.0,90.0,97.0,NaN,Yes,NaN,NaN,NaN
